# Generated by Microsoft365DSC from https://export.microsoft365dsc.com on 7/16/2024, 3:16:52 PM
# Visit https://microsoft365dsc.com for more information

$c = Get-Credential -credential canasmarin@hugeng.onmicrosoft.com

# Exporting resources using credentials
Export-M365DSCConfiguration -Credential $c