<#
.DESCRIPTION
	This script performs network printer mappings with PowerShell and is auto generated by the intune-printer-mapping-generator.
	When executed under SYSTEM authority a scheduled task is created to ensure recurring script execution on each user logon.

.NOTES
	Author: Nicola Suter, nicolonsky tech: https://tech.nicolonsky.ch
#>

[CmdletBinding()]
Param()

###########################################################################################
# Helper function to determine a users group membership
###########################################################################################

# Kudos for Tobias Renström who showed me this!
function Get-ADGroupMembership {
	param(
		[parameter(Mandatory = $true)]
		[string]$UserPrincipalName
	)

	process {

		try {

			if ([string]::IsNullOrEmpty($env:USERDNSDOMAIN) -and [string]::IsNullOrEmpty($searchRoot)) {
				Write-Error "Security group filtering won't work because `$env:USERDNSDOMAIN is not available!"
				Write-Warning "You can override your AD Domain in the `$searchRoot variable"
			}
			else {

				# if no domain specified fallback to PowerShell environment variable
				if ([string]::IsNullOrEmpty($searchRoot)) {
					$searchRoot = $env:USERDNSDOMAIN
				}

				$searcher = New-Object -TypeName System.DirectoryServices.DirectorySearcher
				$searcher.Filter = "(&(userprincipalname=$UserPrincipalName))"
				$searcher.SearchRoot = "LDAP://$searchRoot"
				$distinguishedName = $searcher.FindOne().Properties.distinguishedname
				$searcher.Filter = "(member:1.2.840.113556.1.4.1941:=$distinguishedName)"

				[void]$searcher.PropertiesToLoad.Add("name")

				$list = [System.Collections.Generic.List[String]]@()

				$results = $searcher.FindAll()

				foreach ($result in $results) {
					$resultItem = $result.Properties
					[void]$List.add($resultItem.name)
				}

				$list
			}
		}
		catch {
			#Nothing we can do
			Write-Warning $_.Exception.Message
		}
	}
}

#check if running as system
function Test-RunningAsSystem {
	[CmdletBinding()]
	param()
	process {
		return [bool]($(whoami -user) -match "S-1-5-18")
	}
}


#Testing if groupmembership is given for user
function Test-GroupMembership {
    [CmdletBinding()]
    param (
        $printerMappingConfig,
        $groupMemberships
    )
    try {
        $obj = foreach ($d in $printerMappingConfig) {
            if (-not ([string]::IsNullOrEmpty($($d.GroupFilter)))) {
                foreach ($filter in $($d.GroupFilter)) {
                    if ($groupMemberships -contains $filter) {
                        $d
                    }
                    else {
                        #no match for group
                    }
                }
            }
            else {
                $d 
            }
        }
        $obj
    }
    catch {
        Write-Error "Unknown error testing group memberships: $($_.Exception.Message)"
    }
}

###########################################################################################
# Start transcript for logging
###########################################################################################

Start-Transcript -Path $(Join-Path "$env:temp" "PrinterMapping.log")

###########################################################################################
# Input values from json
###########################################################################################
Write-Output "Running as SYSTEM: $(Test-RunningAsSystem)"

if (-not (Test-RunningAsSystem)) {

    $MappingJson = "$env:APPDATA\Sunrise\PrinterMappings.json"
    if (-not (Test-Path $MappingJson)) {
        Write-Warning "File '$MappingJson' doesn't exist. Printer mapping will not be done."
        Exit 0
    }

    $PrinterMappings = Get-Content -LiteralPath $MappingJson -Raw | ConvertFrom-Json -ErrorAction Stop

    #used to create an array for groups
    $printerMappingConfig = foreach ($d in $($PrinterMappings.Mappings)) {
        [PSCustomObject]@{
            PrintServer = $($d.PrintServer)
            Default     = $($d.Default)
            PrinterName = $($d.PrinterName)
            Id          = $($d.Id)
            GroupFilter = $($d.GroupFilter -split ",")
        }
    }
    Write-Output "Mappings from json: "
    $($printerMappings.Mappings)
    
    # Override with your Active Directory Domain Name e.g. 'ds.nicolonsky.ch' if you haven't configured the domain name as DHCP option
    $searchRoot = ""

    # Get current group membership for the group filter capabilities
    if ($printerMappingConfig.GroupFilter) {
    	try {
    		$groupMemberships = Get-ADGroupMembership -UserPrincipalName $(whoami -upn)
    	}
    	catch {
    		Write-Error $_ -ErrorAction Continue
    	}
    }
}

###########################################################################################
# Mapping network printers
###########################################################################################
#Get PowerShell printers and rename properties

if (-not (Test-RunningAsSystem)) {

	# only map printers where group membership applicable
	$printerMappingConfig = Test-GroupMembership -printerMappingConfig $printerMappingConfig -groupMemberships $groupMemberships

	#iterate through all network printer configuration entries
	foreach ($printer in $printerMappingConfig) {

		Try {
			Write-Output "Get the status of the printer '$($Printer.PrintServer)' on the print server"
			$PrinterServerStatus = "Online"
			Try {
				$PrinterServerStatus = (Get-Printer -ComputerName (([URI]($Printer.PrintServer)).host) -Name $Printer.PrinterName -ErrorAction Stop).PrinterStatus
			} Catch {
				Write-Warning "Could not query printer status from remote print server: $_. Proceeding anyway."
			}
			# Only perform check if the printer on the print server is not offline
			If ($PrinterServerStatus -ne "Offline") {
				# Map printer if it doesn't already exist locally
				If (!(Get-Printer -Name $Printer.PrintServer -ErrorAction SilentlyContinue)){
					Write-Output "Printer not mapped, adding '$($Printer.PrintServer)'"
					Add-Printer -ConnectionName $Printer.PrintServer
					if($Printer.Default -eq 1 -or $Printer.Default -eq "1"){
						$printerInstance = Get-CimInstance -Class Win32_Printer -Filter "Name='$($Printer.PrintServer)'"
						Invoke-CimMethod -InputObject $printerInstance -MethodName SetDefaultPrinter
					}
				}
			} else {
				Write-Output "Printer is offline or Spooler not running"
				$Printer
			}
		} Catch {
			Write-Error "Failed to map the printer $($Printer.PrinterName) - $($Printer.PrintServer)"
			Write-Error $_.Exception.Message
		}
	}
}

###########################################################################################
# End & finish transcript
###########################################################################################

Stop-transcript

###########################################################################################
# Done
###########################################################################################

#!SCHTASKCOMESHERE!#

###########################################################################################
# If this script is running under system (IME) scheduled task is created  (recurring)
###########################################################################################

if (Test-RunningAsSystem) {

	Start-Transcript -Path $(Join-Path -Path "$env:ProgramData\Microsoft\IntuneManagementExtension\Logs" -ChildPath "IntuneprinterMappingScheduledTask.log")
	Write-Output "Running as System --> creating scheduled task which will run on user logon"

	###########################################################################################
	# Get the current script path and content and save it to the client
	###########################################################################################

	$currentScript = Get-Content -Path $($PSCommandPath)

	$schtaskScript = $currentScript[(0) .. ($currentScript.IndexOf("#!SCHTASKCOMESHERE!#") - 1)]

	$scriptSavePath = $(Join-Path -Path $env:ProgramData -ChildPath "Sunrise")

	if (-not (Test-Path $scriptSavePath)) {

		New-Item -ItemType Directory -Path $scriptSavePath -Force
	}

	$scriptSavePathName = "printerMapping.ps1"

	$scriptPath = $(Join-Path -Path $scriptSavePath -ChildPath $scriptSavePathName)

	$schtaskScript | Out-File -FilePath $scriptPath -Force

	###########################################################################################
	# Create dummy vbscript to hide PowerShell Window popping up at logon
	###########################################################################################

	$vbsDummyScript = "
	Dim shell,fso,file

	Set shell=CreateObject(`"WScript.Shell`")
	Set fso=CreateObject(`"Scripting.FileSystemObject`")

	strPath=WScript.Arguments.Item(0)

	If fso.FileExists(strPath) Then
		set file=fso.GetFile(strPath)
		strCMD=`"powershell -nologo -executionpolicy ByPass -command `" & Chr(34) & `"&{`" &_
		file.ShortPath & `"}`" & Chr(34)
		shell.Run strCMD,0
	End If
	"

	$scriptSavePathName = "IntuneprinterMapping-VBSHelper.vbs"

	$dummyScriptPath = $(Join-Path -Path $scriptSavePath -ChildPath $scriptSavePathName)

	$vbsDummyScript | Out-File -FilePath $dummyScriptPath -Force

	$wscriptPath = Join-Path $env:SystemRoot -ChildPath "System32\wscript.exe"

	###########################################################################################
	# Register a scheduled task to run for all users and execute the script on logon
	###########################################################################################

	$schtaskName = "SRMW-IntuneprinterMapping"
	$schtaskDescription = "Map network printers from intune-printer-mapping-generator."

    $trigger = New-ScheduledTaskTrigger -AtLogOn

    $class = cimclass MSFT_TaskEventTrigger root/Microsoft/Windows/TaskScheduler
    $trigger2 = $class | New-CimInstance -ClientOnly
    $trigger2.Enabled = $True
    $trigger2.Subscription = '<QueryList><Query Id="0" Path="Microsoft-Windows-NetworkProfile/Operational"><Select Path="Microsoft-Windows-NetworkProfile/Operational">*[System[Provider[@Name=''Microsoft-Windows-NetworkProfile''] and EventID=10002]]</Select></Query></QueryList>'

    $trigger3 = $class | New-CimInstance -ClientOnly
    $trigger3.Enabled = $True
    $trigger3.Subscription = '<QueryList><Query Id="0" Path="Microsoft-Windows-NetworkProfile/Operational"><Select Path="Microsoft-Windows-NetworkProfile/Operational">*[System[Provider[@Name=''Microsoft-Windows-NetworkProfile''] and EventID=4004]]</Select></Query></QueryList>'

    #Execute task in users context
    $principal= New-ScheduledTaskPrincipal -GroupId "S-1-5-32-545" -Id "Author"

    #call the vbscript helper and pass the PosH script as argument
    $action = New-ScheduledTaskAction -Execute $wscriptPath -Argument "`"$dummyScriptPath`" `"$scriptPath`""

    $settings= New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries

    $null=Register-ScheduledTask -TaskName $schtaskName -Trigger $trigger,$trigger2,$trigger3 -Action $action  -Principal $principal -Settings $settings -Description $schtaskDescription -Force

    Start-ScheduledTask -TaskName $schtaskName
    stop-Transcript
}
###########################################################################################
# Done
###########################################################################################