<#
.SYNOPSIS
    SPO-010 | Analyze Logged Files for SharePoint Online Migration Compatibility.

.DESCRIPTION
    PowerShell script that reads the CSV inventory produced by SPO-009 and validates each file 
    against SharePoint Online limits: path length (< 400 chars), file size (< 15GB), restricted extensions, 
    and document age. Splits files into 'import.csv' and 'noimport.csv' with diagnostic logs.

.PRODUCT
    SharePoint Online / Migration

.ORIGINAL_AUTHOR
    Toni Pohl, Christoph Wilfing, Martina Grom - atwork.at

.MAINTAINER
    Josep Canas - M365 Solutions Architect (SPO-010 classification)

.VERSION
    1.0

.NOTES
    Name: SPO-010_Migration-CheckFiles-Analyze.ps1
    Requires: Semicolon-delimited CSV output file generated by SPO-009.
#>

#region ── Parameters ─────────────────────────────────────────────────────────
# The csv file to analyze (created with SPO-009_Migration-CheckFiles-Scan.ps1).
$Path = ".\SPO-Migration-CheckFiles-files-demo.csv"
# The resulting files to import and to ignore.
$Import = ".\import.csv"
$NoImport = ".\noimport.csv"
# The date to identify old files. 
# Add the months or years that identify how long files are considered to be valid for importing.
$age = (Get-Date).AddYears(-1)
# In SharePoint, the limit for a document's URL is 400 characters long. Adapt as needed.
$MaxURLLength = 400
# Define the maximum file size to be imported. In SPO, the max file size is 15*1GB (as of May 2020, 100GB in future).
[bigint]$MaxSize = 15GB

# Add the file name extension that exclude files to be imported, e.g. ".exe", etc.
$IgnoreExtensions = @(
    '.cache',
    '.cat',
    '.cer',
    '.cfg',
    '.chm',
    '.config',
    '.crt',
    '.dat',
    '.db',
    '.dll',
    '.edb',
    '.exe',
    '.grd',
    '.inf',
    '.ini',
    '.iso',
    '.lnk',
    '.lock',
    '.manifest',
    '.msi',
    '.ocx',
    '.plg',
    '.pst',
    '.ptn',
    '.ptn',
    '.req',
    '.sig',
    '.sis',
    '.spm',
    '.sys',
    '.url',
    '.vhd',
    '.vhdx',
    '.vss',
    '.xen'  
)
#endregion

#region ── Main Program ───────────────────────────────────────────────────────
# Let's start the process...
$csv = Import-Csv -Path $Path -Delimiter ";"

# Delete existing result files if existing.
if ([System.IO.File]::Exists($Import)) { Remove-Item $Import }
if ([System.IO.File]::Exists($NoImport)) { Remove-Item $NoImport }

# Create new result arrays.
$ResultImport = New-Object -TypeName System.Collections.ArrayList
$ResultNoImport = New-Object -TypeName System.Collections.ArrayList

# Initializing.
Write-Host "Check: Working on files." -NoNewline
$CountAll = $csv.Length
$CountYes = 0
$CountNo = 0
$count = 1 # we start with a header...

# Start the loop thru the csv files.
foreach ($line in $csv) { 

    # For each line, we are using flags for the result. We want to add all info why a file is ignored in the comment.
    $ok = $true
    $comment = ""
    $count++

    # Adapt the date format of your CSV as needed. In our sample, the csv file contains the last modified date as here:
    # Date format in CSV: 22/05/2019 10:44:47
    $helper = [DateTime]::ParseExact($line.LastWriteTime, 'dd/MM/yyyy HH:mm:ss', [System.Globalization.CultureInfo]::GetCultureInfo("de-DE"))

    # Check if one of the following conditions is met.
    if ($helper -le $age) {
        $ok = $false
        $comment += "Too old. "
    }
    if ("" -ne $IgnoreExtensions.Where({ $line.FullName.ToLower().EndsWith($_) })) {
        $ok = $false
        $comment += "Ignored file extension. "
    }
    if ([bigint]$line.Length -gt $MaxSize) {
        $ok = $false
        $comment += "Too big ($([bigint]$line.Length/1GB) GB, max. $($MaxSize/1GB) GB). "
    }
    if ($line.FullName.Length -gt $MaxURLLength) {
        $ok = $false
        $comment += "URL too long ($([int]$line.FullName.Length) chars, max. $($MaxURLLength) chars). "
    }

    # Write the files info to the import list or to the noimport list.
    # We include the original line number in the result as a reference in the comment field.
    if ($ok) {
        $CountYes++
        [void]$ResultImport.Add([PSCustomObject]@{
                Filename = $line.FullName
                Size     = $line.Length
                Date     = $line.LastWriteTime
                Comment  = "Line $count."
            })
    }
    else {
        $CountNo++
        [void]$ResultNoImport.Add([PSCustomObject]@{
                Filename = $line.FullName
                Size     = $line.Length
                Date     = $line.LastWriteTime
                Comment  = "Line $count. $comment"
            })
    }
}

# Show a summary and write the csv result files to disk.
Write-Host "`nCompleted."
Write-Host "`nLines: $CountAll`nImport: $CountYes`nNoImport: $CountNo"
$ResultImport | Export-Csv -Delimiter ";" -NoClobber -NoTypeInformation -Encoding UTF8 -Path $Import
$ResultNoImport | Export-Csv -Delimiter ";" -NoClobber -NoTypeInformation -Encoding UTF8 -Path $NoImport
Write-Host "`nCheck $Import and $NoImport.`n"
#endregion
